agent_name: "BC_DAGGER"

model:
  actor_net: "fc_2layers_64units"
  actor_init_output_scale: 0.01
  actor_std_type: "FIXED"
  action_std: 0.2
  critic_net: "fc_2layers_64units"

optimizer:
  type: "Adam"
  learning_rate: 3e-4

discount: 0.99
steps_per_iter: 200
iters_per_output: 5
test_episodes: 20

exp_buffer_size: 50000
batch_size: 256
update_epochs: 30

bc_pretrain_iters: 15
dagger_teacher_prob: 0.7
dagger_teacher_prob_decay: 0.98

entropy_coef: 0.0
action_bound_weight: 0.0

teacher_agent_config:
  agent_name: "PPO"

  model:
    actor_net: "fc_2layers_64units"
    actor_init_output_scale: 0.01
    actor_std_type: "FIXED"
    action_std: 0.6
    critic_net: "fc_2layers_64units"

  actor_optimizer:
    type: "Adam"
    learning_rate: 3e-4

  critic_optimizer:
    type: "Adam"
    learning_rate: 3e-4   

  discount: 0.99
  steps_per_iter: 2048
  iters_per_output: 10
  test_episodes: 10

  batch_size: 256
  update_epochs: 10
  clip_eps: 0.15          
  gae_lambda: 0.95
  critic_coef: 0.5

  entropy_coef: 0.01      
  norm_adv_clip: 5.0
  action_bound_weight: 0.0

teacher_model_file: "output/pointmass_ppo_model.pt"